multiplier: 1

# Set this to TRUE to completely remove the default experience drop
default rewards disabled: false

# Default experience type (can be set to VIRTUAL and CURRENCY)
reward type: experience

# The item to drop when awarding currency. Remove it if you want to give 
# currency directly.
economy drop: slime ball

# The value of each currency item.
economy drop worth: 1

# How many seconds to wait before broadcasting an identical message
message max rate: 5

# When using the VIRTUAL reward type, experience will only be granted 
# automatically for actions that can be directly traced to the player. Mobs 
# that die from traps will instead drop experience orbs if there are other 
# players within this radius:
virtual scan radius: 20

# The default channel to use. If you're not using HeroChat, 
# use the default channels GLOBAL, WORLD or PRIVATE.
default channels: [global]

# Enchanting settings
maximum enchant level: 30
maximum bookcase count: 15 

# If disabled, the permission system is partially disabled - all game features will be 
# granted to every player indiscriminately, except keep experience. Administrative 
# persmission (such as experiencemod.admin) are unaffected, and accessible to 
# operators by default.
use permissions: true

# Mobs can be selected by name|death_case|[spawner]|[baby]|[tamed]:
mobs:
  enderman:
    first: 1
    last: 10
  # Matches all mobs that have spawned from a monster spawner
  #  ?|spawner: 0
  # Disable XP from mobs that are killed with splash potions
  #  ?|magic: 0
  
# Player kills
player death:
  #name|group|death_cause|[murder]
  
# Generic rewards
player:
  fishing success: [2, 5]
  fishing failure: 0

 # Select items using name|durability
 # Select potions with potion|potion type|level|[extended]|[splash]
 #
 #  Trigger/action     Description
 #   block source        Block mined without silk touch. 
 #   bonus               Block mined.
 #   smelting result     Smelted items.
 #   crafting result     Crafted items.
 #   brewing result      Brewed potions.
 #   placing result      Placed blocks.
items:
  coal ore:
    block source: [1, 3]
  lapis ore:
    block source: [3, 10]
  glowing redstone ore, redstone ore:
    block source: [3, 10]
  diamond ore:
    block source: 
      default: [15, 25] # Give the default reward type
      message: '{player} got one DIAMOND and {experience} exp!'
      channels: [global]
  mob spawner:
    bonus:
      first: 30
      last: 50
  coal|0:
    smelting result: [1, 3]
  coal|1:
    smelting result: 1
  wool dye|4:
    smelting result: [3, 10]
  redstone:
    smelting result: [3, 10]
  diamond:
    smelting result: [15, 25]
  iron ingot:
    smelting result: [5, 12]
  gold ingot:
    smelting result: [7, 15]
  stone:
    smelting result: 1
  diamond axe:
    crafting result: 30
  diamond boots:
    crafting result: 40
  diamond chestplate:
    crafting result: 80
  diamond helmet:
    crafting result: 50
  diamond hoe:
    crafting result: 20
  diamond leggings:
    crafting result: 70
  diamond pickaxe:
    crafting result: 30
  diamond spade:
    crafting result: 10
  diamond sword:
    crafting result: 20
  enchantment table:
    crafting result: 20
  jukebox:
    crafting result: 10
  potion|regen|1:
    brewing result: 10
  potion|fire resistance|1:
    brewing result: 12
  potion|instant damage|1:
    brewing result: 15
  potion|instant heal|1:
    brewing result: 15
  potion|poison|1:
    brewing result: 4
  potion|speed|1:
    brewing result: 4
  potion|weakness|1:
    brewing result: 4
  potion|strength|1:
    brewing result: 10
 
# Change how much experience is needed to level up 
levels:
  # Uncomment to revert to 1.2.5 experience leveling
  #0 - Infinity: floor(7 + 3.5*level)