package com.comphenix.xp.history;

public class HistoryException extends Exception {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 488463245930915705L;

	public HistoryException() {
		super();
	}
	
	public HistoryException(String message, Throwable cause) {
		super(message, cause);
	}

	public HistoryException(String message) {
		super(message);
	}

	public HistoryException(Throwable cause) {
		super(cause);
	}
	
	public static HistoryException fromFormat(String message, Object... params) {
		return new HistoryException(String.format(message, params));
	}
}
