package com.comphenix.xp.lookup;

public class ParsingException extends Exception {

	/**
	 * Automatically generated by Eclipse.
	 */
	private static final long serialVersionUID = 343348850011666848L;

	public ParsingException() {
		super();
	}
	
	public ParsingException(String message, Throwable cause) {
		super(message, cause);
	}

	public ParsingException(String message) {
		super(message);
	}

	public ParsingException(Throwable cause) {
		super(cause);
	}
	
	public static ParsingException fromFormat(String message, Object... params) {
		return new ParsingException(String.format(message, params));
	}
}
